/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import font.SetFont;

/**
 *
 * @author kenlee
 */
public class showtime extends javax.swing.JFrame {
    private SetFont font;

    /**
     * Creates new form showtime
     */
    public showtime() {
        font = new SetFont();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        movieID = new javax.swing.JLabel();
        movieBox = new javax.swing.JComboBox<>();
        roomID = new javax.swing.JLabel();
        roomBox = new javax.swing.JComboBox<>();
        showtime = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        seat = new javax.swing.JLabel();
        seatText = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        Jdate = new com.toedter.calendar.JDateChooser();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        showtittle = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 688));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBackground(new java.awt.Color(195, 170, 170, 123));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movieID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        movieID.setText("Movie ID:");
        jPanel3.add(movieID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 102, 45));

        jPanel3.add(movieBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 284, 45));

        roomID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomID.setText("Room ID:");
        jPanel3.add(roomID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 102, 33));

        jPanel3.add(roomBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 284, 44));

        showtime.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        showtime.setText("Show Time:");
        jPanel3.add(showtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 102, 33));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 152, 41));

        date.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date.setText("Show Date:");
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 102, 33));

        seat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        seat.setText("Available Seat: ");
        jPanel3.add(seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, -1, 33));

        seatText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel3.add(seatText, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 196, 44));

        price.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        price.setText("Price:");
        jPanel3.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 76, 32));

        priceText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel3.add(priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 196, 44));

        Jdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Jdate.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 15));
        jPanel3.add(Jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 196, 45));

        insert.setBackground(new java.awt.Color(102, 23, 26));
        insert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        insert.setForeground(new java.awt.Color(255, 255, 255));
        insert.setText("Insert");
        jPanel3.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 162, 51));

        delete.setBackground(new java.awt.Color(102, 23, 26));
        delete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 165, 51));

        edit.setBackground(new java.awt.Color(102, 23, 26));
        edit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 163, 51));

        ok.setBackground(new java.awt.Color(102, 23, 26));
        ok.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ok.setForeground(new java.awt.Color(255, 255, 255));
        ok.setText("Ok");
        jPanel3.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 150, 51));

        cancel.setBackground(new java.awt.Color(102, 23, 26));
        cancel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        jPanel3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, 150, 51));

        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBackground(new java.awt.Color(226, 226, 229));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie ID", "Room ID", "Show time ", "Show Date ", "Available seat", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setBounds(new java.awt.Rectangle(20, 40, 1150, 260));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1160, 270));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1200, 580));

        showtittle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        font.setFontRobotoBold(showtittle, 24f);
        showtittle.setText("Show time");
        jPanel4.add(showtittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 170, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1280, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cinéverse (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 690));

        jPanel1.add(jPanel2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showtime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Jdate;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel date;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> movieBox;
    private javax.swing.JLabel movieID;
    private javax.swing.JButton ok;
    private javax.swing.JLabel price;
    private javax.swing.JTextField priceText;
    private javax.swing.JComboBox<String> roomBox;
    private javax.swing.JLabel roomID;
    private javax.swing.JLabel seat;
    private javax.swing.JTextField seatText;
    private javax.swing.JLabel showtime;
    private javax.swing.JLabel showtittle;
    // End of variables declaration//GEN-END:variables
}
